export const Constants = {
    LOCAL_STORAGE_ARRAY : "zipCodes",
    MSG_ZIP_ALREADY_EXIST : "Entered zipCode is already in the list below",
    MSG_ZIP_ADDED : "Entered zipCode was successfully added",
    MSG_ZIP_DELETED : "ZipCode was successfully deleted",
    MSG_ZIP_NOT_DELETED : "ZipCode could not be deleted",
    APP_ID : "5a4b2d457ecbef9eb2a71e480b947604",
    CURRENT_WEATHER_URL: "https://api.openweathermap.org/data/2.5/weather?zip=",
    FORECAST_5DAYS_WEATHER_URL: "https://api.openweathermap.org/data/2.5/forecast/daily?zip=",
    APP_ID_PARAM : "&appid=",
    OPERATION_GET_CURRENT_WEATHER: "getCurrentWeather",
    OPERATION_GET_FORECAST_5DAYS: "getForecast5DaysWeather",
    MSG_ERROR_GET_CURRENT_WEATHER: "It was not possible to retrieve the weather for the zipCode inserted",
    MSG_ERROR_GET_FORECAST_5DAYS: "It was not possible to retrieve 5 days forecast for the zipCode inserted",
    IMG_SOURCE_SUN : "https://www.angulartraining.com/images/weather/sun.png",
    IMG_SOURCE_SNOW : "https://www.angulartraining.com/images/weather/snow.png",
    IMG_SOURCE_RAIN : "https://www.angulartraining.com/images/weather/rain.png",
    IMG_SOURCE_CLOUDS : "https://www.angulartraining.com/images/weather/clouds.png",
    SUN: "Clear",
    SNOW: "Snow",
    RAIN: "Rain",
    CLOUDS: "Clouds"
}